### ISSUE TITLE
Google chrome slider effects source device slider 

### ISSUE THREAD

**Issue by fonso003** [KillerBOSS2019/TouchPortal-Windows-MediaMixer#3]
Hi! When I create an app specific slider for chrome.exe then attempt to use the slider on my touch device it will also move the slider for whichever device is set to default.

**Comment by DamienStaebler** [comment]
Could you send me a log of this? And maybe a video if possible

**Comment by fonso003** [comment]
`18:30:54.703 - [LOG] (State System) Changed state KillerBOSS.TP.Plugins.Windows.livetime from 1:00:49:41 to value 1:00:49:42
18:30:54.752 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "shortId": "sicu933aph945qfg", "value": "24"}
18:30:54.769 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "connectorId": "pc_com.github.KillerBOSS2019.WinMediaMixer_com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol|com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol.data.slidercon
18:30:54.985 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "shortId": "sicu933aph945qfg", "value": "24"}
18:30:55.002 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "connectorId": "pc_com.github.KillerBOSS2019.WinMediaMixer_com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol|com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol.data.slidercon
18:30:55.216 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "shortId": "sicu933aph945qfg", "value": "24"}
18:30:55.230 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "connectorId": "pc_com.github.KillerBOSS2019.WinMediaMixer_com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol|com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol.data.slidercon
18:30:55.453 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "shortId": "sicu933aph945qfg", "value": "24"}
18:30:55.474 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "connectorId": "pc_com.github.KillerBOSS2019.WinMediaMixer_com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol|com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol.data.slidercon
18:30:55.686 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "shortId": "sicu933aph945qfg", "value": "24"}
18:30:55.703 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "connectorId": "pc_com.github.KillerBOSS2019.WinMediaMixer_com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol|com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol.data.slidercon
18:30:55.715 - [LOG] (Plugin Instance) Incoming data: {"type": "stateUpdate", "id": "KillerBOSS.TP.Plugins.Windows.livetime", "value": "1:00:49:43"}
18:30:55.715 - [LOG] (State System) Changed state KillerBOSS.TP.Plugins.Windows.livetime from 1:00:49:42 to value 1:00:49:43
18:30:55.922 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "shortId": "sicu933aph945qfg", "value": "24"}
18:30:55.945 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "connectorId": "pc_com.github.KillerBOSS2019.WinMediaMixer_com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol|com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol.data.slidercon
18:30:56.171 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "shortId": "sicu933aph945qfg", "value": "24"}
18:30:56.197 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "connectorId": "pc_com.github.KillerBOSS2019.WinMediaMixer_com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol|com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol.data.slidercon
18:30:56.410 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "shortId": "sicu933aph945qfg", "value": "24"}
18:30:56.426 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "connectorId": "pc_com.github.KillerBOSS2019.WinMediaMixer_com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol|com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol.data.slidercon
18:30:56.649 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "shortId": "sicu933aph945qfg", "value": "24"}
18:30:56.662 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "connectorId": "pc_com.github.KillerBOSS2019.WinMediaMixer_com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol|com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol.data.slidercon
18:30:56.721 - [LOG] (Plugin Instance) Incoming data: {"type": "stateUpdate", "id": "KillerBOSS.TP.Plugins.Windows.livetime", "value": "1:00:49:44"}
18:30:56.723 - [LOG] (State System) Changed state KillerBOSS.TP.Plugins.Windows.livetime from 1:00:49:43 to value 1:00:49:44
18:30:56.880 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "shortId": "sicu933aph945qfg", "value": "24"}
18:30:56.896 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "connectorId": "pc_com.github.KillerBOSS2019.WinMediaMixer_com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol|com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol.data.slidercon
18:30:57.115 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "shortId": "sicu933aph945qfg", "value": "24"}
18:30:57.134 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "connectorId": "pc_com.github.KillerBOSS2019.WinMediaMixer_com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol|com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol.data.slidercon
18:30:57.352 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "shortId": "sicu933aph945qfg", "value": "24"}
18:30:57.368 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "connectorId": "pc_com.github.KillerBOSS2019.WinMediaMixer_com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol|com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol.data.slidercon
18:30:57.592 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "shortId": "sicu933aph945qfg", "value": "24"}
18:30:57.608 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "connectorId": "pc_com.github.KillerBOSS2019.WinMediaMixer_com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol|com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol.data.slidercon
18:30:57.724 - [LOG] (Plugin Instance) Incoming data: {"type": "stateUpdate", "id": "KillerBOSS.TP.Plugins.Windows.livetime", "value": "1:00:49:45"}
18:30:57.726 - [LOG] (State System) Changed state KillerBOSS.TP.Plugins.Windows.livetime from 1:00:49:44 to value 1:00:49:45
18:30:57.825 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "shortId": "sicu933aph945qfg", "value": "24"}
18:30:57.844 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "connectorId": "pc_com.github.KillerBOSS2019.WinMediaMixer_com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol|com.github.KillerBOSS2019.WinMediaMixer.connector.APPcontrol.data.slidercon
18:30:58.076 - [LOG] (Plugin Instance) Incoming data: {"type": "connectorUpdate", "shortId": "sicu933aph945qfg", "value": "24"}`

**Comment by fonso003** [comment]
https://user-images.githubusercontent.com/19594820/211176951-4150dbd8-d8a5-4261-9363-d9a5ef96f8c3.MOV

**Comment by DamienStaebler** [comment]
Ah very interesting. Does this happen to other applications? Like does it only happen to `cod.exe`?

**Comment by fonso003** [comment]
It does. I changed it to other apps and it does the same thing. The more sliders I add the weirder the behavior

**Comment by fonso003** [comment]
Looks like it might be an issue when the sliders are next to each other. 

https://user-images.githubusercontent.com/19594820/211178341-3a36f916-390c-4c30-ad0e-a9e798ec3cbe.MOV

**Comment by DamienStaebler** [comment]
Oh wow that's very strange. It seems like it's TP's fault instead but I'll double check the programming as well.

**Comment by DamienStaebler** [comment]
Hm I am guessing that page is bugged out. So could you try to create a new page and create two separate slides right next to each other. And lmk if it still happens.

**Comment by fonso003** [comment]
Will do. I find it weird that no matter which slider I move the api is sent the same ID

**Comment by DamienStaebler** [comment]
Okay so I got confirmed that this is a bug on the TP side. The fix right now would just click the refresh button. This bug should be fixed in the next TP update ( not plugin update )

**Comment by fonso003** [comment]
Thanks so much and sorry for wasting your time. Refreshing the client does fix it!

**Comment by DamienStaebler** [comment]
Ah glad that worked. No problem at all.
