### ISSUE TITLE
Touch Portal issue code E3081

### ISSUE THREAD

**Issue by buzzbros2002** [KillerBOSS2019/TouchPortal-Windows-MediaMixer#6]
When using the plugin after the most recent Touch Portal 4 update, there's an error that reads the following.

------
Plug-in Performance Issue detected

The plug-in 'TouchPortal Windows Media Mixer'  is not functioning correctly. It is currently impacting the performance of Touch Portal. We advise you to contact the plug-in dev. The issue code is E3081
------

**Comment by spacey42** [comment]
Same.

**Comment by LePlay99** [comment]
Same Problem

**Comment by morgantic** [comment]
Same here.

**Comment by leuthier** [comment]
Hi guys, there is a commit waiting for review #5 that fixed this issue.

**Comment by Chablo954** [comment]
Getting this error currently

**Comment by DamienStaebler** [comment]
This should be solved in next version

**Comment by DamienStaebler** [comment]
This should be solved in next version

**Comment by Bootscreen** [comment]
This sounds awesome, can you tell us when you release it?

**Comment by Bootscreen** [comment]
any news about it?
